stages:
  - test
  - build
  - deploy
cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules

test:
  image: node:lts-alpine
  stage: test
  script:
    - yarn install
    - yarn run vue-cli-service test:unit
    - yarn build
  artifacts:
    paths:
      - "dist"

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  needs:
    - test

deploy:
  stage: deploy
  image: google/cloud-sdk
  script:
    - gcloud auth activate-service-account --key-file $GCLOUD_KEY_FILE
    - gcloud config set project frontend-342617
    - gcloud config set compute/zone us-central1-a
    - gcloud container clusters create cluster-for-backend --num-nodes=3
    - gcloud container clusters get-credentials cluster-for-backend
    - kubectl apply -f backend-app.yaml
